<?php
/**
 * Template Name: Privacy Policy Page
 */
get_header(); ?>

<section class="page-hero" style="background:var(--navy);padding:80px 0 60px;">
  <div class="container">
    <?php echo gpsclinic_breadcrumb(); ?>
    <h1 style="color:var(--white);margin-top:16px;">Privacy <span style="color:var(--orange);">Policy</span></h1>
    <p style="color:var(--muted);font-size:.95rem;margin-top:10px;">Last updated: September 2024 &nbsp;|&nbsp; <strong style="color:var(--orange);">Requires legal review before publication.</strong></p>
  </div>
</section>

<section class="section" style="padding:72px 0;">
  <div class="container" style="max-width:760px;">

    <div class="post-content">

      <div style="background:#FFF3CD;border:1px solid #FFC107;border-radius:10px;padding:20px 24px;margin-bottom:40px;">
        <strong>Legal Review Required:</strong> This privacy policy is a draft template. It must be reviewed and approved by a qualified legal professional before GPS Clinic publishes or distributes this document. Verify compliance with the Information Technology (Amendment) Act 2008, IT (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules 2011, and the Digital Personal Data Protection Act 2023.
      </div>

      <h2>1. Introduction</h2>
      <p>GPS Clinic ("we", "us", "our") is committed to protecting the personal information of our clients, website visitors, and users of our GPS tracking services. This Privacy Policy explains what data we collect, how we use it, how we store it, and your rights in relation to it.</p>
      <p>By using our website (gpsclinic.co.in) or our GPS tracking platform, you agree to the practices described in this policy.</p>

      <h2>2. Information We Collect</h2>
      <h3>2.1 Information You Provide</h3>
      <ul>
        <li>Name, mobile number, email address, and business name submitted via enquiry forms</li>
        <li>Vehicle registration numbers and fleet details provided during onboarding</li>
        <li>Driver names and contact numbers added to the tracking platform</li>
      </ul>

      <h3>2.2 Information Collected Automatically</h3>
      <ul>
        <li>Vehicle GPS coordinates, speed, heading, and ignition status from installed tracking devices</li>
        <li>IP address and browser type when you visit our website</li>
        <li>Cookies used to maintain your session on our web platform (essential cookies only)</li>
      </ul>

      <h3>2.3 Information We Do Not Collect</h3>
      <p>We do not collect payment card numbers directly. Payments are processed via third-party gateways. We do not collect biometric data.</p>

      <h2>3. How We Use Your Information</h2>
      <ul>
        <li>To provide and operate the GPS tracking service you have subscribed to</li>
        <li>To respond to enquiries and provide customer support</li>
        <li>To send service-related notifications (device offline, subscription renewal)</li>
        <li>To generate reports you have requested</li>
        <li>To comply with AIS 140 / VAHAN data-sharing obligations to the Government of India</li>
        <li>To improve our services and troubleshoot technical issues</li>
      </ul>

      <h2>4. Vehicle Location Data</h2>
      <p>Vehicle location data generated by our tracking devices belongs to the registered fleet operator (our client). GPS Clinic processes this data solely to deliver the tracking service. We do not sell, share, or transfer vehicle location data to third parties, except:</p>
      <ul>
        <li>Where required by law (e.g., VAHAN / MoRTH AIS 140 reporting obligations)</li>
        <li>Where you have explicitly authorised sharing (e.g., sharing a live tracking link with a customer)</li>
        <li>Where required to prevent imminent harm (e.g., stolen vehicle recovery in co-operation with law enforcement)</li>
      </ul>

      <h2>5. Data Retention</h2>
      <ul>
        <li>Trip history and location data: retained for 90 days on standard plans; up to 3 years on enterprise plans</li>
        <li>Enquiry form submissions: retained for 12 months</li>
        <li>Support ticket records: retained for 24 months</li>
        <li>Invoice and payment records: retained for 7 years (statutory requirement)</li>
      </ul>

      <h2>6. Data Security</h2>
      <p>We implement industry-standard security measures including HTTPS-only access to our platform, encrypted storage of credentials, and restricted access to production databases. However, no internet transmission is 100% secure, and we cannot guarantee absolute security.</p>

      <h2>7. Your Rights</h2>
      <p>Under applicable Indian law, you have the right to:</p>
      <ul>
        <li>Request access to the personal data we hold about you</li>
        <li>Request correction of inaccurate data</li>
        <li>Request deletion of your data (subject to legal retention obligations)</li>
        <li>Withdraw consent for marketing communications</li>
      </ul>
      <p>To exercise these rights, contact us at <a href="mailto:privacy@gpsclinic.co.in">privacy@gpsclinic.co.in</a>.</p>

      <h2>8. Cookies</h2>
      <p>Our website uses essential session cookies only. We do not use advertising or analytics cookies without your consent. You can disable cookies in your browser settings, but this may affect login functionality on our platform.</p>

      <h2>9. Third-Party Services</h2>
      <p>We use the following third-party services which may process data on our behalf:</p>
      <ul>
        <li>Google Maps API (for displaying map data in the tracking platform)</li>
        <li>Payment gateways (for processing subscription payments)</li>
        <li>SMS / WhatsApp API providers (for alert delivery)</li>
      </ul>
      <p>Each provider has its own privacy policy governing data they process.</p>

      <h2>10. Children</h2>
      <p>Our services are not directed at individuals under 18. We do not knowingly collect personal data from children. If a school bus operator provides us with parent contact details for the parent app, those contacts are used only to deliver tracking notifications and are not processed for any other purpose.</p>

      <h2>11. Changes to This Policy</h2>
      <p>We may update this policy periodically. We will notify active subscribers of material changes via email or platform notification. Continued use of the service after the effective date constitutes acceptance of the updated policy.</p>

      <h2>12. Contact</h2>
      <p>For privacy-related queries or complaints:</p>
      <address style="font-style:normal;background:var(--bg);padding:20px 24px;border-radius:10px;margin-top:12px;">
        GPS Clinic<br>
        Shop No. 110, Kailash Market<br>
        Padampura Circle, Railway Station Road<br>
        Chhatrapati Sambhajinagar (Aurangabad) - 431005<br>
        Maharashtra, India<br>
        Email: <a href="mailto:privacy@gpsclinic.co.in">privacy@gpsclinic.co.in</a><br>
        Phone: <a href="tel:+919876543210">+91 98765 43210</a>
      </address>

    </div>

  </div>
</section>

<?php get_template_part('template-parts/cta-band', null, [
  'title'    => 'Questions About Your Data?',
  'subtitle' => 'Contact our team for any privacy-related queries. We respond within one business day.',
  'cta_label'=> 'Contact Us',
]); ?>

<?php get_footer(); ?>
